---
development:
  cloud_name: dnwdiewqs
  api_key: '846931796985656'
  api_secret: 25k0HfXlKgh-4PgitJYgkr5uerk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dnwdiewqs
  api_key: '846931796985656'
  api_secret: 25k0HfXlKgh-4PgitJYgkr5uerk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dnwdiewqs
  api_key: '846931796985656'
  api_secret: 25k0HfXlKgh-4PgitJYgkr5uerk
  enhance_image_tag: true
  static_file_support: false
